//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.10 at 12:40:03 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.be.vdab.countries", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package be.vdab.landen.soapmessages;
